# Generated by Django 6.0.2 on 2026-03-01 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='e.g. Car models, brand, or shelf location')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
