# Generated by Django 6.0.2 on 2026-03-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.BigIntegerField(default=0, help_text='The absolute lowest price for bargaining'),
            preserve_default=False,
        ),
    ]
