# Generated by Django 6.0.3 on 2026-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.BigIntegerField(default=0, help_text='The absolute lowest price for bargaining'),
        ),
    ]
